### ISSUE TITLE
Lean WP break Reading Settings

### ISSUE THREAD

**Issue by proweb** [senlin/lean-wp#10]
Hello thanks for such usefull plugin
But I have small problem when it active.

If Lean WP active wordpress "Reading Settings" always set Front page displays to Static page

---

[Screen record](https://www.useloom.com/share/853abb3ee0f94f9bab22d3e713d21a63)

**Comment by senlin** [comment]
Hi Sergey, thanks for your message and glad to hear you like Lean WP.

The plugin indeed sets the Front page displays setting to Static page. 

In the [plugin docs](https://so-wp.com/lean-wp-docs/backend/features#set-reading-settings-front-page-displays-to-page) you can read more about that.

Hope that helps.

Piet

**Comment by proweb** [comment]
So @senlin it's feature not bug???

**Comment by senlin** [comment]
Certainly **not** a bug, as per the earlier referred to docs:

> Most company websites come with a dedicated home page, instead of showing the latest Post like blogs do. Lean WP automatically sets the Front page displays-setting (under Settings > Reading) to A static page. The user can then select the correct page from the drop down.

**Comment by proweb** [comment]
ОК. It's your plugin, your vision.

**Comment by senlin** [comment]
You often make company sites which show the latest posts as homepage?

**Comment by proweb** [comment]
I want to use plugin for cleanup all garbage on my blog, but this "feature"  made it not usable

**Comment by senlin** [comment]
Interesting that you would want to use the plugin on a blog, whereas I built it with company sites in mind.

Tell you what, I have just released a version where you can add a filter to the functions file of your (child-)theme that overrides the filter and function in the plugin, like so:

```
/**
 * override Lean WP filter to show latest posts on homepage
 */
add_filter( 'pre_option_show_on_front', 'show_page_on_front' );

function show_page_on_front() {
    return 'posts';
}
```

Hope that helps
