### ISSUE TITLE
Tools

### ISSUE THREAD

**Issue by asha23** [senlin/lean-wp#12]
I noticed that this plugin removed the Tools menu from my installation. Not sure if this is a feature or a bug, but thought I'd flag it.

That's where Migrate DB lives - I couldn't access it.

Really like what this plugin does - Saves a lot of time.

**Comment by senlin** [comment]
Hi @asha23 

From the [documentation](https://so-wp.com/lean-wp-docs/backend/features#remove-dashboard-widgets-and-removes-certain-admin-sidebar-sub-menus) (emphasis mine):

> Also the admin sidebar can use some cleaning up, with Lean WP activated **the Tools menu is no longer there** and from the Appearance it removes the submenu pages of Custom Header, Custom Background and Edit CSS (since WP 4.8).

Migrate DB is not gone, just not directly accessible anymore. If you write down the link, you'll see it's still there.
