### ISSUE TITLE
Metas en html

### ISSUE THREAD

**Issue by shoropio** [senlin/lean-wp#13]
Hola, me gusta mucho este plugin, me preguntaba si podrían agregar una función de eliminar del html la metas que se eliminen, por ejemplo: Al desactivarse los pingbacks que se elimine del html link rel="pingback" href="http://www.example.com/xmlrpc.php" y así sucesivamente con lo que se elimine.

**Comment by senlin** [comment]
Hola, not entirely clear what it is exactly that you would like the plugin to do? Could you please clarify a bit more?

**Comment by shoropio** [comment]
Claro, su plugin desactiva correctamente los pingbacks, pero en el html de mi sitio web siempre se imprime la meta link rel="pingback" href="http://www.example.com/xmlrpc.php". aunque estén desactivados los pingbacks del sitio cuando reviso mi código fuente está la meta link. Por ejemplo yo podría eliminar la meta link de mi tema pero lo ropería una actualización futura del tema.

**Comment by senlin** [comment]
Ah okay, I think I understand. Thanks for the additional explanation.

I will need to check this and see if/how I can remove the link. Will update this thread when I know more.

**Comment by senlin** [comment]
No time to address, closing this for now. Feel free to re-open if you make a PR available.
