### ISSUE TITLE
Allow Tools menu or Settings panel

### ISSUE THREAD

**Issue by zaccety** [senlin/lean-wp#16]
Hi,

Another request for a settings menu for more granular control over what's hidden/removed.

Specifically I'd like access back to the Tools menu as not only is this where Migrate DB lives (I know it's still accessible as per ticket https://github.com/senlin/lean-wp/issues/12 and that there are alternatives to this plugin) but it's also where the Export/Erase personal data and import/export menu's are.

Can this menu be re-activated with a function or do I have to abandon it (which I don't really want to do).

Cheers,

Zac

**Comment by senlin** [comment]
@zaccety 

I'll look into it

**Comment by born2webdesign** [comment]
That really would be greatly appreciated!
For now I have to hack `includes/class-lean-wp.php`
commenting
```
remove_menu_page(` 'tools.php' );
```
and prevent the plugin from auto-updating:
```
add_filter(
	'auto_update_plugin',
	function ( $update, $item ) {
		return ( ! in_array( $item->slug, array(
			// Commented `tools` menu removal.
			'lean-wp',
		) ) );
	},
	10,
	2
);
```

**Comment by zaccety** [comment]
Hey man, any news on this, seems a little more critical now the Tools menu includes the new Site Health stuff...

**Comment by senlin** [comment]
By all means send a PR, I have very little time lately

**Comment by senlin** [comment]
Released [v1.3.1](https://github.com/senlin/lean-wp/releases/tag/v1.3.1) which brings back tools menu.
Closing this ticket

**Comment by born2webdesign** [comment]
Great, thank you!
Might I add that I wouldn’t consider this request ‘whining’ (as per code comment) ;)

**Comment by zaccety** [comment]
haha!

Yeah, hardly whining wanting to be able to export/erase user data in align with GDPR requirements :)

Thanks for updating.

**Comment by senlin** [comment]
> Yeah, hardly whining wanting to be able to export/erase user data in align with GDPR requirements :)

Those tools have **always** been available to you. Removing the tools menu does in fact not remove access to those sub-menus, so the comment is less misplaced actually :)

Also any one of you could have very easily sent a PR that adds the `//` to bring back the tools menu, because that is all this version update was.
