### ISSUE TITLE
incompatibilty notice

### ISSUE THREAD

**Issue by zaccety** [senlin/lean-wp#17]
Have just updated WP to 5.3 and am receiving the following warning in dashboard:

Warning: Declaration of WPDI_Plugin_Installer_Skin::feedback($string) should be compatible with WP_Upgrader_Skin::feedback($string, ...$args) in ...\wp-content\plugins\lean-wp\vendor\afragen\wp-dependency-installer\wp-dependency-installer.php on line 434

**Comment by senlin** [comment]
Thanks for the report, I will update the WP Dependency Installer, which will solve the issue. I will update this ticket once done. Apologies for the inconvenience.

**Comment by senlin** [comment]
Thanks for your patience, new version committed, please note min. PHP version increased.

**Comment by zaccety** [comment]
Nice one, thanks for the quick updated, love this plugin.
