### ISSUE TITLE
Also remove "Howdy" in other languages

### ISSUE THREAD

**Issue by senlin** [senlin/lean-wp#2]
The plugin only removes "Howdy", but leaves translations of it.

Originally reported by Melanie Shepherd on [Facebook](https://www.facebook.com/groups/wordpresspluginsuggestions/permalink/1530060183707540/?comment_id=1530123250367900&comment_tracking=%7B%22tn%22%3A%22R0%22%7D)

Now the question of course becomes whether or not the translations of "Howdy" are also irritating for the users of that particular translated version or not?

On the one hand I can imagine that a translated (and localised) version of Howdy, does not necessarily has to come across as rude, whereas "Howdy" is exactly that for many non-Americans.

Input very welcome before deciding on how to go with this!

**Comment by mommaroodles** [comment]
It would be nice to remove that too - I'm all a lean WP - the lighter the better

**Comment by senlin** [comment]
Yeah, I'm leaning towards that too, just remove the whole greeting thing. Will be easier to put together too :)

**Comment by senlin** [comment]
With the release of version 1.1.0 referenced here, we have removed Howdy and the user/display-name altogether, which should solve this issue.
