### ISSUE TITLE
Customizer question

### ISSUE THREAD

**Issue by verysiberian** [senlin/lean-wp#5]
Hello! Thanks for Lean WP -- just installed it and seems great. Call me lame, but I actually use some features of the Customizer. Would appreciate it if you would add a settings page (so that the plugin is not quite so strict -- all or nothing) and that such a page would allow the Customizer to remain.

Thanks!

**Comment by senlin** [comment]
Hi thanks for your feedback and no, I won't call you lame ;)

Settings page has been requested before and I'm still thinking about it. What I can do though is to change the way the Customizer Remove All Parts plugin has been included. If I make it optional, then the user can decide to use it or to leave it uninstalled.

I would be interested to know which features of the Customizer you actually use?

**Comment by verysiberian** [comment]
Thanks for considering my suggestion. In my case, I am using the Material Gaze theme, which is a child theme of the Stargazer theme. I need to modify some of the CSS to tweak how a few elements render, but don't want to edit the child theme directly since I would lose the changes in any future update. As such, I am using the Customizer's extra CSS function.

Best,
Rob

**Comment by verysiberian** [comment]
Thanks for making those dependencies optional! I just updated and am able to use the customizer again. :)

There is a message appearing, though, on every page of my WP backend:

[Dependency] To make the most of the Lean WP plugin, installing and activating the Customizer Remove All Parts plugin is highly recommended. Install Now »

Even when I click the X to dismiss the message, it keeps appearing on each page. I have cleared my cache but it is still present. Is there a way to disable this message permanently?

Best,
Rob

**Comment by senlin** [comment]
Hi Rob,
Glad you like it :)
I must say that I have experienced what you are experiencing in the past too, but that it disappeared after a while. 
When that was happening I contacted @afragen, the developer of the WP Dependency Installer to ask him about it, which you can see in [this thread](https://github.com/afragen/wp-dependency-installer/issues/1#issuecomment-302851696)
Does that help you in any way?
Piet

**Comment by verysiberian** [comment]
Interesting. I tried disabling caching but it’s still there. Your update today was still an improvement and the added functionality makes the nagging notification worth tolerating. Perhaps the author of that particular plugin will fix it at some point.

Best regards,
Rob

**Comment by senlin** [comment]
I will check with @afragen (Andy Fragen, the author of the WP Dependency Installer) if there is any quickfix to this problem.

PS @verysiberian many thanks for adjusting your rating from 4 to 5 stars over at the [WP Plugins Directory](https://wordpress.org/support/plugin/lean-wp/reviews/)

**Comment by afragen** [comment]
I'll take a look. There is no built-in method to dismiss an admin notice though I thought I included a class to do this. I'll check and report back.

**Comment by afragen** [comment]
Just a quick thought. I think you need to initialize the PaND library in your main plugin file similarly to https://github.com/afragen/github-updater/blob/develop/github-updater.php#L71-L76

If this is the issue I clearly need to add this to my example, sorry.

**Comment by senlin** [comment]
> Just a quick thought. I think you need to initialize the PaND library in your main plugin file similarly to https://github.com/afragen/github-updater/blob/develop/github-updater.php#L71-L76

With an eye on https://github.com/afragen/wp-dependency-installer/issues/1#issuecomment-323497876 I take it that this no longer is the issue?

**Comment by afragen** [comment]
That was my hope. Initialize PaND inside of wp-dependency-installer.php

I’ll need to test still to see if it solves the issue.

**Comment by senlin** [comment]
> I’ll need to test still to see if it solves the issue.

on my end it does :)

**Comment by senlin** [comment]
Hi Rob @verysiberian 
The dismissible notice issue now is fixed too with the release of [version 1.1.1](https://github.com/senlin/lean-wp/releases/tag/v1.1.1).
Hope you like it and I will close this issue now :)
