### ISSUE TITLE
question with no content, OP probably changed his mind...

### ISSUE THREAD

**Issue by coldwetbloke** [senlin/lean-wp#7]

**Comment by senlin** [comment]
@coldwetbloke 
???

**Comment by coldwetbloke** [comment]
Sorry - I solved my own problem just after posting. I closed case with
intention of deleting - but no way to delete?!


From: Piet Bos <notifications@github.com> <notifications@github.com>
Reply: senlin/lean-wp
<reply@reply.github.com>
<reply@reply.github.com>
Date: 5 September 2017 at 11:18:32
To: senlin/lean-wp <lean-wp@noreply.github.com> <lean-wp@noreply.github.com>
Cc: coldwetbloke <jctribbeck@gmail.com> <jctribbeck@gmail.com>, Mention
<mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [senlin/lean-wp] removal of WP's default plugins (#7)

@coldwetbloke <https://github.com/coldwetbloke>
???

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/senlin/lean-wp/issues/7#issuecomment-327134351>, or mute
the thread

**Comment by senlin** [comment]
I believe there indeed is no way to delete something (in the spirit of version control perhaps?).

Next time something like this happens, it might be a good idea to add what you did to solve your problem (as opposed to deleting your original question), if only for others who might have the same issue.

**Comment by coldwetbloke** [comment]
👍 fair point.
