### ISSUE TITLE
Disable gravatars

### ISSUE THREAD

**Issue by mattradford** [senlin/lean-wp#9]
Consider adding support to disable gravatars by default, e.g.	

```
if ( get_option( 'show_avatars' ) === '1' ) {
	update_option( 'show_avatars', '' );
} 
```

This would have to be optional as some themes may visually break.

**Comment by senlin** [comment]
Hi Matt, thanks for your input.

Have you seen this https://github.com/senlin/lean-wp/blob/master/includes/class-lean-wp.php#L434-L435 ;)

I'm still thinking whether or not to implement a settings page to make things like this optional.

**Comment by mattradford** [comment]
Sorry, missed that!

Settings is a double-edged sword. Decisions v choices... ;)

**Comment by senlin** [comment]
No worries, there are a lot of little things that I have tried to include; easy to miss one/some...

> Settings is a double-edged sword. Decisions v choices... ;)

It certainly is, apart from the work that goes into building it and keeping it up to date :)
